# Generated by Django 4.1.6 on 2023-04-07 13:04

import book.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.IntegerField(default=book.models.Book.generate_id, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('book', models.FileField(upload_to=book.models.store_book, verbose_name='Book File')),
                ('book_id', models.CharField(max_length=60)),
                ('price', models.FloatField(validators=[django.core.validators.MaxValueValidator(1000000.0), django.core.validators.MinValueValidator(1.0)])),
            ],
        ),
    ]
