# Generated by Django 4.1.6 on 2023-02-13 16:09

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book',
            field=models.FileField(unique=True, upload_to=book.models.store_book, verbose_name='Book File'),
        ),
    ]
