# Generated by Django 4.1.6 on 2023-04-10 02:45

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_purchasedbooks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover_page',
            field=models.ImageField(default='', upload_to=book.models.store_cover, verbose_name='Cover Page'),
            preserve_default=False,
        ),
    ]
