# Generated by Django 4.1.6 on 2023-04-10 04:07

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_alter_book_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.PositiveBigIntegerField(default=book.models.Book.generate_id, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
