# Generated by Django 4.1.6 on 2023-04-10 18:01

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('book', '0006_alter_book_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='purchasedbooks',
            unique_together={('book', 'user')},
        ),
    ]
